---@meta
---@diagnostic disable: lowercase-global
---@diagnostic disable: missing-return
--[[
Functions and constants for interacting with Photon Fusion
This is a generated file. Do not modify. Created using https://github.com/britzl/generatedocs
--]]

---@class defold_api.fusion
---@field OWNERMODE_TRANSACTION number
---@field OWNERMODE_PLAYERATTACHED number
---@field OWNERMODE_DYNAMIC number
---@field OWNERMODE_MASTERCLIENT number
---@field OWNERMODE_GAMEGLOBAL number
---@field STATE_DISCONNECTED number
---@field STATE_CONNECTING number
---@field STATE_CONNECTED number
---@field STATE_JOININGROOM number
---@field STATE_INROOM number
---@field STATE_LEAVINGROOM number
---@field STATE_DISCONNECTING number
---@field DISCONNECT_CAUSE_NONE number
---@field DISCONNECT_CAUSE_DISCONNECTBYSERVERUSERLIMIT number
---@field DISCONNECT_CAUSE_EXCEPTIONONCONNECT number
---@field DISCONNECT_CAUSE_DISCONNECTBYSERVER number
---@field DISCONNECT_CAUSE_DISCONNECTBYSERVERLOGIC number
---@field DISCONNECT_CAUSE_TIMEOUTDISCONNECT number
---@field DISCONNECT_CAUSE_EXCEPTION number
---@field DISCONNECT_CAUSE_INVALIDAUTHENTICATION number
---@field DISCONNECT_CAUSE_MAXCCUREACHED number
---@field DISCONNECT_CAUSE_INVALIDREGION number
---@field DISCONNECT_CAUSE_OPERATIONNOTALLOWEDINCURRENTSTATE number
---@field DISCONNECT_CAUSE_CUSTOMAUTHENTICATIONFAILED number
---@field DISCONNECT_CAUSE_CLIENTVERSIONTOOOLD number
---@field DISCONNECT_CAUSE_CLIENTVERSIONINVALID number
---@field DISCONNECT_CAUSE_DASHBOARDVERSIONINVALID number
---@field DISCONNECT_CAUSE_AUTHENTICATIONTICKETEXPIRED number
---@field DISCONNECT_CAUSE_DISCONNECTBYOPERATIONLIMIT number
---@field MASTER_CLIENT_PLAYER_ID number
---@field PLUGIN_PLAYER_ID number
---@field OBJECT_OWNER_PLAYER_ID number
---@field REPLICATION_MODE_NONE number
---@field REPLICATION_MODE_AUTO number
---@field EVENT_OBJECT_READY number
---@field EVENT_SUB_OBJECT_CREATED number
---@field EVENT_OBJECT_DESTROYED number
---@field EVENT_SUB_OBJECT_DESTROYED number
---@field EVENT_OBJECT_FORCE_ALIVE number
---@field EVENT_SUB_OBJECT_FORCE_ALIVE number
---@field EVENT_OBJECT_OWNER_CHANGED number
---@field EVENT_PREDICTION_OVERRIDE number
---@field EVENT_LOBBY_STATS number
---@field EVENT_ROOM_JOINED number
---@field EVENT_ROOM_LEFT number
---@field EVENT_RPC number
---@field EVENT_MAP_CHANGE number
---@field EVENT_DESTROYED_MAP_ACTOR number
---@field EVENT_INTEREST_ENTER number
---@field EVENT_INTEREST_EXIT number
---@field EVENT_FORCED_DISCONNECT number
---@field EVENT_FUSION_START number
---@field EVENT_CONNECTED number
---@field EVENT_DISCONNECTED number
fusion = {}
---@param app_id string
---@param app_version string
function fusion.init(app_id,app_version) end
function fusion.init_from_settings() end
---@param user string?
function fusion.connect(user) end
function fusion.disconnect() end
function fusion.reconnect() end
function fusion.start() end
function fusion.stop() end
---@return number Connection
function fusion.get_state() end
---@return number Disconnect
function fusion.get_disconnect_cause() end
---@param create_room_options table
---@param matchmaking_options table
function fusion.join_or_create_room_random(create_room_options,matchmaking_options) end
---@param matchmaking_options table
function fusion.join_room_random(matchmaking_options) end
---@param room_name string
---@param join_room_options table
function fusion.join_room(room_name,join_room_options) end
---@param room_name string
---@param create_room_options table
---@param join_room_options table
function fusion.join_or_create_room(room_name,create_room_options,join_room_options) end
---@param room_name string
---@param create_room_options table
function fusion.create_room(room_name,create_room_options) end
---@param will_come_back boolean
---@param send_auth_cookie boolean
function fusion.leave_room(will_come_back,send_auth_cookie) end
---@return boolean connected
function fusion.is_connected() end
---@return boolean running
function fusion.is_running() end
---@return boolean started
function fusion.is_started() end
---@return boolean in_room
function fusion.is_in_room() end
---@param enable boolean
function fusion.enable_debug(enable) end
---@param map number
---@param owner_mode number
---@param properties table
---@param id string?
function fusion.create_map_object(map,owner_mode,properties,id) end
---@param factory_url string
---@param position vector3?
---@param rotation quat?
---@param map number
---@param owner_mode number
---@param script_properties table
---@return hash Id
function fusion.spawn(factory_url,position,rotation,map,owner_mode,script_properties) end
---@param id string?
function fusion.despawn(id) end
---@param map number
---@param factory_url string
---@param owner_mode number
---@param options table
---@param id string?
function fusion.create_object(map,factory_url,owner_mode,options,id) end
---@param id string?
function fusion.destroy_object(id) end
---@param index number
---@param sequence number
---@param data string
function fusion.map_change(index,sequence,data) end
---@param target_player number
---@param data table
---@return boolean ok
function fusion.send_rpc(target_player,data) end
function fusion.subscribe_rpc() end
function fusion.unsubscribe_rpc() end
---@param listener function
function fusion.on_event(listener) end
---@return number The
function fusion.get_local_player_id() end
---@param id string?
---@return number The
function fusion.get_owner_id(id) end
---@param id string?
---@return boolean authority
function fusion.has_authority(id) end
---@param id string?
---@return boolean True
function fusion.has_owner(id) end
---@param claim_ownership boolean
---@param id string?
function fusion.want_authority(claim_ownership,id) end
---@param id string?
function fusion.clear_owner_cooldown(id) end
---@param send_rate number
---@param id string?
function fusion.set_room_send_rate(send_rate,id) end
---@param send_rate number
---@param id string?
function fusion.set_local_send_rate(send_rate,id) end
---@param id string?
function fusion.reset_room_send_rate(id) end
---@return number count
function fusion.player_count() end
---@return boolean master
function fusion.is_master_client() end
---@return number rtt
function fusion.get_rtt() end
---@return number time
function fusion.get_network_time() end
---@return number diff
function fusion.network_time_diff() end
function fusion.set_global_interest_key() end
function fusion.set_area_interest_key() end
function fusion.set_user_interest_key() end
---@param keys table
function fusion.set_area_keys(keys) end
function fusion.add_user_key() end
function fusion.remove_user_key() end
