embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/example/assets/models/platformerkit/crate.glb\"\n"
  "skeleton: \"/example/assets/models/platformerkit/crate.glb\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"colormap\"\n"
  "  material: \"/builtins/materials/model_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/example/assets/models/platformerkit/colormap.png\"\n"
  "  }\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_DYNAMIC\n"
  "mass: 1.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"crate\"\n"
  "mask: \"player\"\n"
  "mask: \"floor\"\n"
  "mask: \"wall\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_BOX\n"
  "    position {\n"
  "      y: 0.25\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 3\n"
  "  }\n"
  "  data: 0.25\n"
  "  data: 0.25\n"
  "  data: 0.25\n"
  "}\n"
  ""
}
