components {
  id: "player"
  component: "/example/player.script"
}
embedded_components {
  id: "model"
  type: "model"
  data: "mesh: \"/example/assets/models/characters/Knight.glb\"\n"
  "skeleton: \"/example/assets/models/characters/Knight.glb\"\n"
  "animations: \"/example/assets/models/characters/Knight.glb\"\n"
  "default_animation: \"T-Pose\"\n"
  "name: \"{{NAME}}\"\n"
  "materials {\n"
  "  name: \"knight_texture\"\n"
  "  material: \"/builtins/materials/model_skinned_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/example/assets/models/characters/knight_texture.png\"\n"
  "  }\n"
  "}\n"
  "materials {\n"
  "  name: \"knight_texture_no_skin\"\n"
  "  material: \"/builtins/materials/model_instanced.material\"\n"
  "  textures {\n"
  "    sampler: \"tex0\"\n"
  "    texture: \"/example/assets/models/characters/knight_texture.png\"\n"
  "  }\n"
  "}\n"
  ""
}
embedded_components {
  id: "collisionobject"
  type: "collisionobject"
  data: "type: COLLISION_OBJECT_TYPE_KINEMATIC\n"
  "mass: 0.0\n"
  "friction: 0.1\n"
  "restitution: 0.5\n"
  "group: \"player\"\n"
  "mask: \"floor\"\n"
  "mask: \"wall\"\n"
  "mask: \"crate\"\n"
  "embedded_collision_shape {\n"
  "  shapes {\n"
  "    shape_type: TYPE_SPHERE\n"
  "    position {\n"
  "      y: 0.5\n"
  "    }\n"
  "    rotation {\n"
  "    }\n"
  "    index: 0\n"
  "    count: 1\n"
  "  }\n"
  "  data: 0.5\n"
  "}\n"
  ""
}
