[fusion]
title = Fusion
help = Settings for Photon Fusion
group = Runtime

app_id.type = string

app_version.type = string
app_version.default = 1.0

default_region.type = string
default_region.default = eu
default_region.options = eu,us
