go.property("factory", msg.url())
go.property("remote_object", false)

function init(self)
	print("init", go.get_id(), self.remote_object, os.date())
	assert(go.exists(self.factory))
	if not self.remote_object then
		msg.post("#", "register_object")
	end
end

function final(self)
	print("final", go.get_id())
	if not self.remote_object then
		fusion.destroy(go.get_id())
	end
end

function on_message(self, message_id, message, sender)
	if message_id == hash("register_object") then
		print("init", go.get_id())
		local scene = 0
		print("calling fusion.register()", go.get_id())
		fusion.register(go.get_id(), scene, self.factory)
	end
end