go.property("factory", msg.url())
go.property("is_scene_object", false)

function init(self)
	--print("init", go.get_id(), "date", os.date(), "has_authority", fusion.has_authority(), "has_owner", fusion.has_owner())
	assert(go.exists(self.factory))
	local scene = 0
	if self.is_scene_object then
		print("calling fusion.register_scene_object()", go.get_id())
		fusion.register_scene_object(scene, self.factory, fusion.OWNERMODE_MASTERCLIENT)
	else
		print("calling fusion.register_object()", go.get_id())
		fusion.register_object(scene, self.factory, fusion.OWNERMODE_PLAYERATTACHED)
	end
end

function final(self)
	print("final", go.get_id())
	if fusion.has_authority() then
		fusion.unregister_object()
	end
end
